<a href="https://colab.research.google.com/github/sviss-home/netology_education/blob/main/s_h_h_w_statistics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy  as np

In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv') #чтение данных из url

df.columns =['surgery?', 'Age', 'Hospital Num', 'rect.temp', 'pulse', 'r.rate', 't.of.ext', 'periph pulse', 'mucous membranes', 'capillary refill time', 
             'pain', 'peristalsis', 'abdominal distension', 'nasogastric tube', 'nasogastric reflux', 'nasogastric reflux PH', 'rectal examination - feces', 
             'abdomen', 'packed cell volume', 'total protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome', 'surgical lesion?',
             'type of lesion1', 'type of lesion2', 'type of lesion3', 'cp_data'] #названия для столбцов

df_cutted = df.loc[:, ['surgery?', 'Age', 'rect.temp', 'pulse', 'r.rate', 't.of.ext', 'pain', 'outcome']] #вывод нужных столбцов
df_values_replaced = df_cutted.replace('?', np.NaN) #замена ? на NaN
df_values_converted = df_values_replaced.astype(float) #преобразование значений датафрейма в тип данных float

for column in df_values_converted:
    columnSeriesObj = df_values_converted[column]
    print('Осн. стат. показатели для колонки',column,':', 'Min =', min(columnSeriesObj.values), 'Max =',max(columnSeriesObj.values), 'Размах =', (max(columnSeriesObj.values) - min(columnSeriesObj.values)), 'Среднее арифметическое =', np.nanmean(columnSeriesObj.values)) #вычисляем min, max, размах и среднее арифметическое, игнорируя NaN

print(df_values_converted.isna().sum()) #подсчитаем число NaN в каждом столбце

df_values_converted.fillna(0).head() #заменяем пропуски на нули, чтобы сохранить датафрейм в изначальном размере

Осн. стат. показатели для колонки surgery? : Min = 1.0 Max = 2.0 Размах = 1.0 Среднее арифметическое = 1.395973154362416
Осн. стат. показатели для колонки Age : Min = 1.0 Max = 9.0 Размах = 8.0 Среднее арифметическое = 1.6421404682274248
Осн. стат. показатели для колонки rect.temp : Min = 35.4 Max = 40.8 Размах = 5.399999999999999 Среднее арифметическое = 38.166527196652716
Осн. стат. показатели для колонки pulse : Min = 30.0 Max = 184.0 Размах = 154.0 Среднее арифметическое = 71.93454545454546
Осн. стат. показатели для колонки r.rate : Min = 8.0 Max = 96.0 Размах = 88.0 Среднее арифметическое = 30.42738589211618
Осн. стат. показатели для колонки t.of.ext : Min = nan Max = nan Размах = nan Среднее арифметическое = 2.345679012345679
Осн. стат. показатели для колонки pain : Min = 1.0 Max = 5.0 Размах = 4.0 Среднее арифметическое = 2.942622950819672
Осн. стат. показатели для колонки outcome : Min = 1.0 Max = 3.0 Размах = 2.0 Среднее арифметическое = 1.5503355704697988
surgery?      1
Age           0
rect.temp    60
pulse        24
r.rate       58
t.of.ext     56
pain         55
outcome       1
dtype: int64

   surgery?  Age  rect.temp  pulse  r.rate  t.of.ext  pain  outcome
0       1.0  1.0       39.2   88.0    20.0       0.0   3.0      3.0
1       2.0  1.0       38.3   40.0    24.0       1.0   3.0      1.0
2       1.0  9.0       39.1  164.0    84.0       4.0   2.0      2.0
3       2.0  1.0       37.3  104.0    35.0       0.0   0.0      2.0
4       2.0  1.0        0.0    0.0     0.0       2.0   2.0      1.0

1. О хирургии: наличие или отсутствие операции. Наличие нулей в выборке влияет на статитстические показатели, нужно использовать NaN, игнорируя их.
2. Возраст: разделение на два возраста: взорслые и молодые. Наличие NaN в выборке 
3. Ректальная температура
измеряется в дробных числах. Наличие нулей в выборке влияет на статитстические показатели, нужно использовать NaN, игнорируя их.
4. Пульс
измеряется в целых числах. Наличие нулей в выборке влияет на статитстические показатели, нужно использовать NaN, игнорируя их.
5. частота дыхания. Наличие нулей в выборке влияет на статитстические показатели, нужно использовать NaN, игнорируя их.
6. температура конечностей. Наличие нулей в выборке влияет на статитстические показатели, нужно использовать NaN, игнорируя их.
7. уровень влияния болевого воздействия. Наличие нулей в выборке
8. исход - показатель наличия/отсутствия жизни и причин её прекращения. Наличие нулей в выборке